package com.drool.demo.entity;

import com.drool.demo.entity.People

dialect  "java"

rule "man"
    when
        p : People(sex==1 && drlType == "people")
    then
        p.setName("达男");
        System.out.println(p.getName() + "是男孩");
end


rule "girl"
    when
        p : People(sex == 2 &&  drlType == "people")
    then
        System.out.println(p.getName() + "是女孩");
end


rule "girl1"
    when
         $p:People(sex == 1 && drlType == "people",$sex : sex )
    then
        System.out.println("girl规则执行");
        System.out.println($p);
        System.out.println($sex);
end

rule "peopleAndCat"
    when
        People(sex == 1)
        Cat(sex == 1)
    then
        System.out.println("peopleAndCat规则执行");
end
